name:"Hello Actions"

description: "Greet someone"

author: "sahlinmarkp@johndeere.com"



inputs:

  MY_NAME:
  
      description: "Who to greet"
      
      required: true
      
      default: "World"
      
 
 runs:
 
      using: "docker"
      
      image: "Dockerfile"
      
      
 branding:
 
      icon: "mic"
      
      color: "pupple"
